const CONFIG = {

  TERMINAL_BG: '#11111b',
  TERMINAL_SURFACE: '#1e1e2e',
  TERMINAL_BORDER: '#313244',
  TERMINAL_TEXT: '#cdd6f4',
  TERMINAL_SUBTEXT: '#a6adc8',
  TERMINAL_MUTED: '#585b70',
  TERMINAL_ACCENT: '#89b4fa',
  TERMINAL_GREEN: '#a6e3a1',
  TERMINAL_YELLOW: '#f9e2af',
  TERMINAL_RED: '#f38ba8',
  TERMINAL_PINK: '#cba6f7',

  TERMINAL_MENU_CATEGORY: true,
  TERMINAL_MENU_TAG: true,
  TERMINAL_MENU_ARCHIVE: true,
  TERMINAL_MENU_SEARCH: true,

  TERMINAL_PROMPT_CHAR: '~',
  TERMINAL_SIDEBAR: false,
  TERMINAL_POST_LIST_COVER: false,
  TERMINAL_ARTICLE_RECOMMEND_POSTS: true
}
export default CONFIG
